name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Instalamos solo las librerías necesarias (incluyendo pyperclip)
        pip install customtkinter pyrebase4 matplotlib numpy Pillow pyperclip pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        # Usamos --collect-all para asegurar que CustomTkinter funcione bien
        pyinstaller --noconsole --onefile --add-data "logo.png;." --collect-all customtkinter admin_app.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: C-LAB-Admin-Windows
        path: dist/admin_app.exe
