name: Build Windows EXE

on:
  push:
    branches: [ main ] # Se ejecutará cada vez que subas algo a la rama main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Instalación de todas las librerías detectadas en tu código
        pip install customtkinter pyrebase4 matplotlib numpy Pillow pyperclip pyinstaller
        # tcl-bin ayuda a evitar errores de carga de la interfaz gráfica en el EXE
        pip install tcl-bin

    - name: Build EXE with PyInstaller
      run: |
        # --noconsole: Oculta la ventana negra al abrir la app
        # --onefile: Empaqueta todo en un solo archivo .exe
        # --add-data: Incluye el logo dentro del ejecutable
        # --collect-all: Asegura que CustomTkinter se incluya con todos sus temas y json
        pyinstaller --noconsole --onefile --add-data "logo.png;." --collect-all customtkinter admin_app.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: C-LAB-Admin-Windows
        path: dist/admin_app.exe
